### ISSUE TITLE
crash when charging 1.16.1

### ISSUE THREAD

**Issue by BikiniClubRP** [Darkhax-Minecraft/Coins#9]
**when I use their version Coins-1.16.1-2.0.2.jar and Bookshelf-1.16.1-6.2.14.jar photo message appears at the end of mod loading:**
**image:** https://fotos.subefotos.com/437bac6db7db4d3689135b9dff7344abo.png
**LOG:**
[02Aug2020 20:24:06.246] [modloading-worker-1/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 32.0.97, for MC 1.16.1 with MCP 20200625.160719
[02Aug2020 20:24:06.246] [modloading-worker-1/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v32.0.97 Initialized
[02Aug2020 20:24:07.017] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: coins, class net.darkhax.coins.Coins
java.lang.NoSuchMethodError: net.minecraft.util.NonNullList.create()Lnet/minecraft/util/NonNullList;
	at net.darkhax.bookshelf.registry.CommandRegistry.<init>(CommandRegistry.java:38) ~[?:?]
	at net.darkhax.bookshelf.registry.RegistryHelper.<init>(RegistryHelper.java:43) ~[?:?]
	at net.darkhax.coins.Coins.<init>(Coins.java:18) ~[?:2.0.2]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:136) ~[?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) ~[?:32.0]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$11(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_241]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_241]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_241]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_241]
[02Aug2020 20:24:07.019] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: An error occurred while dispatching event CONSTRUCT to coins
[02Aug2020 20:24:07.019] [modloading-worker-0/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 9 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:317) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.afterEvent(FMLModContainer.java:123) ~[?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) ~[?:32.0]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$11(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_241]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_241]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_241]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_241]
[02Aug2020 20:24:07.372] [Render thread/INFO] [net.minecraftforge.fml.DeferredWorkQueue/LOADING]: Dispatching synchronous work after CONSTRUCT: 1 jobs
[02Aug2020 20:24:07.394] [Render thread/INFO] [net.minecraftforge.fml.DeferredWorkQueue/LOADING]: Synchronous work queue completed in 00:00:00.017
[02Aug2020 20:24:07.395] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[02Aug2020 20:24:07.395] [Render thread/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:317) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:111) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:93) ~[?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:149) ~[minecraft.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.1-32.0.97-launcher.jar:32.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?]

**Comment by Darkhax** [comment]
Hello, can you upload the full log file?

**Comment by BikiniClubRP** [comment]
[03Aug2020 11:17:57.056] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, fmlclient, --fml.forgeVersion, 32.0.97, --fml.mcVersion, 1.16.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200625.160719, --username, Oscarin_elx, --version, 1.16.1-forge-32.0.97, --gameDir, C:\Users\Oscar\AppData\Roaming\.technic\modpacks\test-0-perdidas, --assetsDir, C:\Users\Oscar\AppData\Roaming\.technic\assets, --assetIndex, 1.16, --uuid, 944a7482bad24afe9b4c6a5019d80221, --accessToken, ????????, --userType, mojang, --versionType, release, --title, test 0 perdidas, --icon, C:\Users\Oscar\AppData\Roaming\.technic\assets\packs\test-0-perdidas\icon.png]
[03Aug2020 11:17:57.056] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 6.1.1+74+master.966c698 starting: java version 1.8.0_241 by Oracle Corporation
[03Aug2020 11:17:57.557] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[03Aug2020 11:17:57.603] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/Oscar/AppData/Roaming/.technic/cache/org/spongepowered/mixin/0.8/mixin-0.8.jar Service=ModLauncher Env=CLIENT
[03Aug2020 11:17:59.527] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.1-forge-32.0.97, --gameDir, C:\Users\Oscar\AppData\Roaming\.technic\modpacks\test-0-perdidas, --assetsDir, C:\Users\Oscar\AppData\Roaming\.technic\assets, --uuid, 944a7482bad24afe9b4c6a5019d80221, --username, Oscarin_elx, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release, --title, test 0 perdidas, --icon, C:\Users\Oscar\AppData\Roaming\.technic\assets\packs\test-0-perdidas\icon.png]
[03Aug2020 11:17:59.774] [main/INFO] [STDOUT/]: [net.minecraft.client.main.Main:main:80]: Completely ignored arguments: [--title, test 0 perdidas, --icon, C:\Users\Oscar\AppData\Roaming\.technic\assets\packs\test-0-perdidas\icon.png]
[03Aug2020 11:18:13.057] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[03Aug2020 11:18:13.061] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: Oscarin_elx
[03Aug2020 11:18:13.401] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 build 10
[03Aug2020 11:18:16.180] [modloading-worker-2/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: bookshelf, class net.darkhax.bookshelf.Bookshelf
java.lang.NoSuchMethodError: net.minecraft.util.NonNullList.create()Lnet/minecraft/util/NonNullList;
	at net.darkhax.bookshelf.registry.CommandRegistry.<init>(CommandRegistry.java:38) ~[?:?]
	at net.darkhax.bookshelf.registry.RegistryHelper.<init>(RegistryHelper.java:43) ~[?:?]
	at net.darkhax.bookshelf.Bookshelf.<init>(Bookshelf.java:62) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:136) ~[?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) ~[?:32.0]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$11(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_241]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_241]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_241]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_241]
[03Aug2020 11:18:16.183] [modloading-worker-2/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: An error occurred while dispatching event CONSTRUCT to bookshelf
[03Aug2020 11:18:16.183] [modloading-worker-2/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 6 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:317) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.afterEvent(FMLModContainer.java:123) ~[?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) ~[?:32.0]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$11(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_241]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_241]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_241]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_241]
[03Aug2020 11:18:16.191] [modloading-worker-3/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 32.0.97, for MC 1.16.1 with MCP 20200625.160719
[03Aug2020 11:18:16.192] [modloading-worker-3/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v32.0.97 Initialized
[03Aug2020 11:18:16.182] [modloading-worker-1/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: coins, class net.darkhax.coins.Coins
java.lang.NoSuchMethodError: net.minecraft.util.NonNullList.create()Lnet/minecraft/util/NonNullList;
	at net.darkhax.bookshelf.registry.CommandRegistry.<init>(CommandRegistry.java:38) ~[?:?]
	at net.darkhax.bookshelf.registry.RegistryHelper.<init>(RegistryHelper.java:43) ~[?:?]
	at net.darkhax.coins.Coins.<init>(Coins.java:18) ~[?:2.0.2]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:136) ~[?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) ~[?:32.0]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$11(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_241]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_241]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_241]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[?:1.8.0_241]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[?:1.8.0_241]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_241]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_241]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.ModList.lambda$dispatchParallelEvent$12(ModList.java:135) ~[?:?]
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_241]
[03Aug2020 11:18:16.317] [modloading-worker-1/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: An error occurred while dispatching event CONSTRUCT to coins
[03Aug2020 11:18:16.317] [modloading-worker-1/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 7 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:317) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.afterEvent(FMLModContainer.java:123) ~[?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) ~[?:32.0]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$11(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_241]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_241]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_241]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[?:1.8.0_241]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[?:1.8.0_241]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_241]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_241]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.ModList.lambda$dispatchParallelEvent$12(ModList.java:135) ~[?:?]
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_241]
[03Aug2020 11:18:16.946] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 2 errors found
[03Aug2020 11:18:16.946] [Render thread/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:317) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:111) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:93) ~[?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:149) ~[minecraft.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.1-32.0.97-launcher.jar:32.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?]
[03Aug2020 11:18:17.473] [Render thread/WARN] [net.minecraft.client.GameSettings/]: Removed resource pack file/Miau guau.zip from options because it doesn't seem to exist anymore
[03Aug2020 11:18:20.745] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[03Aug2020 11:18:21.417] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Mod Resources, Default
[03Aug2020 11:18:21.642] [Worker-Main-4/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event SETUP, 2 errors found.
[03Aug2020 11:18:21.643] [Worker-Main-4/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event SETUP, 2 errors found
[03Aug2020 11:18:21.643] [Worker-Main-4/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:317) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:111) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:119) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:101) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:109) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_241]
[03Aug2020 11:18:28.300] [Worker-Main-7/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event ENQUEUE_IMC, 2 errors found.
[03Aug2020 11:18:28.301] [Worker-Main-7/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event ENQUEUE_IMC, 2 errors found
[03Aug2020 11:18:28.301] [Worker-Main-7/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:317) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:111) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.finishModLoading(ClientModLoader.java:133) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$4(ClientModLoader.java:103) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniRun(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_241]
[03Aug2020 11:18:28.593] [Render thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[03Aug2020 11:18:28.594] [Render thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[03Aug2020 11:18:29.103] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 1024x512x0 minecraft:textures/atlas/blocks.png-atlas
[03Aug2020 11:18:29.181] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[03Aug2020 11:18:29.182] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[03Aug2020 11:18:29.182] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[03Aug2020 11:18:29.183] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[03Aug2020 11:18:29.184] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[03Aug2020 11:18:29.184] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[03Aug2020 11:18:30.320] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[03Aug2020 11:18:30.322] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[03Aug2020 11:18:30.323] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[03Aug2020 11:18:40.878] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!

**Comment by Darkhax** [comment]
Thanks for providing further information. This log info suggests that something was wrong with your Minecraft environment and the issue could not be reproduced independently. Perhaps you downloaded a "deobf" jar of Bookshelf?
